{{- range .Values.ambassador.consulMappings }}
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ template "concourse.web.fullname" . }}-{{ .ambassador_id }}-consul
spec:
  ambassador_id: {{ .ambassador_id }}
  prefix: {{ .prefix }}
  service: {{ template "concourse.web.fullname" . }}-sidecar-proxy
  resolver: consul-connect-{{ .ambassador_id }}
  tls: ambassador-consul-{{ .ambassador_id }}
  load_balancer:
    policy: round_robin
{{- end }}
